services:
  app:
    build:
      context: $PWD
      dockerfile: $PWD/Dockerfile
    image: execute_simple_query:1.0.0
    container_name: app
    restart: 'always'
  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql